import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import { afterEach, beforeEach, expect, it, vi } from 'vitest';
const mocks = vi.hoisted(() => ({ request: vi.fn(), update: vi.fn(), session: vi.fn(), native: vi.fn() }));
vi.mock('@capacitor/core', () => ({ Capacitor: { isNativePlatform: mocks.native } }));
vi.mock('@/integrations/supabase/client', () => ({ supabase: { auth: { resetPasswordForEmail: mocks.request, updateUser: mocks.update, getSession: mocks.session, onAuthStateChange: () => ({ data: { subscription: { unsubscribe: vi.fn() } } }) } } }));
import PasswordRecoveryPage from './PasswordRecoveryPage';
beforeEach(() => { vi.clearAllMocks(); mocks.native.mockReturnValue(false); mocks.request.mockResolvedValue({error:null}); mocks.update.mockResolvedValue({error:null}); mocks.session.mockResolvedValue({data:{session:{user:{id:'test'}}}}); });
afterEach(cleanup);
function mount(reset=false) { render(<MemoryRouter><PasswordRecoveryPage reset={reset}/></MemoryRouter>); }
it('sends the web redirect and a neutral confirmation', async () => { mount(); fireEvent.change(screen.getByLabelText('Correo de tu cuenta'),{target:{value:'test@example.com'}}); fireEvent.click(screen.getByText('Enviar enlace')); await waitFor(()=>expect(mocks.request).toHaveBeenCalledWith('test@example.com',{redirectTo:`${window.location.origin}/auth/restablecer`})); expect(await screen.findByRole('status')).toHaveTextContent('Si existe una cuenta'); });
it('requests the Android callback', async () => { mocks.native.mockReturnValue(true); mount(); fireEvent.change(screen.getByLabelText('Correo de tu cuenta'),{target:{value:'test@example.com'}}); fireEvent.click(screen.getByText('Enviar enlace')); await waitFor(()=>expect(mocks.request).toHaveBeenCalledWith('test@example.com',{redirectTo:'com.worshiptranspose.app://auth/callback?recovery=1'})); });
it('does not update without a session', async () => { mocks.session.mockResolvedValue({data:{session:null}}); mount(true); await screen.findByText(/Abre el enlace de recuperación/); expect(screen.queryByText('Guardar contraseña')).toBeNull(); expect(mocks.update).not.toHaveBeenCalled(); });
it('rejects mismatched passwords and then saves matching ones', async () => { mount(true); const input=await screen.findByLabelText('Nueva contraseña'); fireEvent.change(input,{target:{value:'newpassword'}}); fireEvent.change(screen.getByLabelText('Confirmar contraseña'),{target:{value:'different'}}); fireEvent.click(screen.getByText('Guardar contraseña')); expect(mocks.update).not.toHaveBeenCalled(); fireEvent.change(screen.getByLabelText('Confirmar contraseña'),{target:{value:'newpassword'}}); fireEvent.click(screen.getByText('Guardar contraseña')); await waitFor(()=>expect(mocks.update).toHaveBeenCalledWith({password:'newpassword'})); expect(await screen.findByRole('status')).toHaveTextContent('Contraseña actualizada'); });
it('keeps the form available after a send failure', async () => { mocks.request.mockResolvedValue({error:{message:'rate limit'}}); mount(); fireEvent.change(screen.getByLabelText('Correo de tu cuenta'),{target:{value:'test@example.com'}}); fireEvent.click(screen.getByText('Enviar enlace')); expect(await screen.findByRole('alert')).toHaveTextContent('No se pudo enviar'); expect(screen.getByText('Enviar enlace')).not.toBeDisabled(); });
